//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : automat.sm
//

#include "automat.h"
#include "automat_sm.h"

using namespace statemap;

// Static class declarations.
AutomatMap_Start AutomatMap::Start("AutomatMap::Start", 0);
AutomatMap_Cs AutomatMap::Cs("AutomatMap::Cs", 1);
AutomatMap_Rs AutomatMap::Rs("AutomatMap::Rs", 2);
AutomatMap_Es AutomatMap::Es("AutomatMap::Es", 3);
AutomatMap_As AutomatMap::As("AutomatMap::As", 4);
AutomatMap_Ts AutomatMap::Ts("AutomatMap::Ts", 5);
AutomatMap_Es2 AutomatMap::Es2("AutomatMap::Es2", 6);
AutomatMap_Space1 AutomatMap::Space1("AutomatMap::Space1", 7);
AutomatMap_Name AutomatMap::Name("AutomatMap::Name", 8);
AutomatMap_Space2 AutomatMap::Space2("AutomatMap::Space2", 9);
AutomatMap_OpenBracket AutomatMap::OpenBracket("AutomatMap::OpenBracket", 10);
AutomatMap_Space3 AutomatMap::Space3("AutomatMap::Space3", 11);
AutomatMap_List AutomatMap::List("AutomatMap::List", 12);
AutomatMap_Comma AutomatMap::Comma("AutomatMap::Comma", 13);
AutomatMap_Space4 AutomatMap::Space4("AutomatMap::Space4", 14);
AutomatMap_Close_bracket AutomatMap::Close_bracket("AutomatMap::Close_bracket", 15);
AutomatMap_As2 AutomatMap::As2("AutomatMap::As2", 16);
AutomatMap_Ss AutomatMap::Ss("AutomatMap::Ss", 17);
AutomatMap_Space5 AutomatMap::Space5("AutomatMap::Space5", 18);
AutomatMap_Name0 AutomatMap::Name0("AutomatMap::Name0", 19);
AutomatMap_Space6 AutomatMap::Space6("AutomatMap::Space6", 20);
AutomatMap_Js AutomatMap::Js("AutomatMap::Js", 21);
AutomatMap_Os AutomatMap::Os("AutomatMap::Os", 22);
AutomatMap_Is AutomatMap::Is("AutomatMap::Is", 23);
AutomatMap_Ns AutomatMap::Ns("AutomatMap::Ns", 24);
AutomatMap_Space7 AutomatMap::Space7("AutomatMap::Space7", 25);
AutomatMap_Name1 AutomatMap::Name1("AutomatMap::Name1", 26);
AutomatMap_Error AutomatMap::Error("AutomatMap::Error", 27);
AutomatMap_Ok AutomatMap::Ok("AutomatMap::Ok", 28);

void AutomatState::EOS(automatContext& context)
{
    Default(context);
}

void AutomatState::Unknown(automatContext& context)
{
    Default(context);
}

void AutomatState::a(automatContext& context)
{
    Default(context);
}

void AutomatState::c(automatContext& context)
{
    Default(context);
}

void AutomatState::c_b(automatContext& context)
{
    Default(context);
}

void AutomatState::ch(automatContext& context)
{
    Default(context);
}

void AutomatState::comma(automatContext& context)
{
    Default(context);
}

void AutomatState::e(automatContext& context)
{
    Default(context);
}

void AutomatState::i(automatContext& context)
{
    Default(context);
}

void AutomatState::j(automatContext& context)
{
    Default(context);
}

void AutomatState::n(automatContext& context)
{
    Default(context);
}

void AutomatState::num(automatContext& context)
{
    Default(context);
}

void AutomatState::o(automatContext& context)
{
    Default(context);
}

void AutomatState::o_b(automatContext& context)
{
    Default(context);
}

void AutomatState::r(automatContext& context)
{
    Default(context);
}

void AutomatState::s(automatContext& context)
{
    Default(context);
}

void AutomatState::sp(automatContext& context)
{
    Default(context);
}

void AutomatState::t(automatContext& context)
{
    Default(context);
}

void AutomatState::Default(automatContext& context)
{
    throw (
        TransitionUndefinedException(
            (context.getState()).getName(),
            context.getTransition()));

}

void AutomatMap_Default::Unknown(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Error);
    context.getState().Entry(context);


}

void AutomatMap_Default::c(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Error);
    context.getState().Entry(context);


}

void AutomatMap_Default::r(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Error);
    context.getState().Entry(context);


}

void AutomatMap_Default::e(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Error);
    context.getState().Entry(context);


}

void AutomatMap_Default::a(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Error);
    context.getState().Entry(context);


}

void AutomatMap_Default::t(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Error);
    context.getState().Entry(context);


}

void AutomatMap_Default::s(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Error);
    context.getState().Entry(context);


}

void AutomatMap_Default::j(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Error);
    context.getState().Entry(context);


}

void AutomatMap_Default::o(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Error);
    context.getState().Entry(context);


}

void AutomatMap_Default::i(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Error);
    context.getState().Entry(context);


}

void AutomatMap_Default::n(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Error);
    context.getState().Entry(context);


}

void AutomatMap_Start::c(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Cs);
    context.getState().Entry(context);


}

void AutomatMap_Cs::r(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Rs);
    context.getState().Entry(context);


}

void AutomatMap_Rs::e(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Es);
    context.getState().Entry(context);


}

void AutomatMap_Es::a(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::As);
    context.getState().Entry(context);


}

void AutomatMap_As::t(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Ts);
    context.getState().Entry(context);


}

void AutomatMap_Ts::e(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Es2);
    context.getState().Entry(context);


}

void AutomatMap_Es2::sp(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Space1);
    context.getState().Entry(context);


}

void AutomatMap_Space1::ch(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Name);
    context.getState().Entry(context);


}

void AutomatMap_Space1::num(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Error);
    context.getState().Entry(context);


}

void AutomatMap_Space1::sp(automatContext& context)
{



}

void AutomatMap_Name::ch(automatContext& context)
{



}

void AutomatMap_Name::num(automatContext& context)
{



}

void AutomatMap_Name::sp(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Space2);
    context.getState().Entry(context);


}

void AutomatMap_Space2::a(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::As2);
    context.getState().Entry(context);


}

void AutomatMap_Space2::o_b(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::OpenBracket);
    context.getState().Entry(context);


}

void AutomatMap_Space2::sp(automatContext& context)
{



}

void AutomatMap_OpenBracket::sp(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Space3);
    context.getState().Entry(context);


}

void AutomatMap_Space3::c_b(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Error);
    context.getState().Entry(context);


}

void AutomatMap_Space3::ch(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::List);
    context.getState().Entry(context);


}

void AutomatMap_Space3::num(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Error);
    context.getState().Entry(context);


}

void AutomatMap_Space3::sp(automatContext& context)
{



}

void AutomatMap_List::ch(automatContext& context)
{



}

void AutomatMap_List::comma(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Comma);
    context.getState().Entry(context);


}

void AutomatMap_List::num(automatContext& context)
{



}

void AutomatMap_List::sp(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Space4);
    context.getState().Entry(context);


}

void AutomatMap_Comma::ch(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::List);
    context.getState().Entry(context);


}

void AutomatMap_Comma::num(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Error);
    context.getState().Entry(context);


}

void AutomatMap_Space4::c_b(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Close_bracket);
    context.getState().Entry(context);


}

void AutomatMap_Space4::sp(automatContext& context)
{



}

void AutomatMap_Close_bracket::EOS(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Ok);
    context.getState().Entry(context);


}

void AutomatMap_As2::s(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Ss);
    context.getState().Entry(context);


}

void AutomatMap_Ss::sp(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Space5);
    context.getState().Entry(context);


}

void AutomatMap_Space5::ch(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Name0);
    context.getState().Entry(context);


}

void AutomatMap_Space5::num(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Error);
    context.getState().Entry(context);


}

void AutomatMap_Space5::sp(automatContext& context)
{



}

void AutomatMap_Name0::ch(automatContext& context)
{



}

void AutomatMap_Name0::num(automatContext& context)
{



}

void AutomatMap_Name0::sp(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Space6);
    context.getState().Entry(context);


}

void AutomatMap_Space6::j(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Js);
    context.getState().Entry(context);


}

void AutomatMap_Space6::sp(automatContext& context)
{



}

void AutomatMap_Js::o(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Os);
    context.getState().Entry(context);


}

void AutomatMap_Os::i(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Is);
    context.getState().Entry(context);


}

void AutomatMap_Is::n(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Ns);
    context.getState().Entry(context);


}

void AutomatMap_Ns::sp(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Space7);
    context.getState().Entry(context);


}

void AutomatMap_Space7::ch(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Name1);
    context.getState().Entry(context);


}

void AutomatMap_Space7::num(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Error);
    context.getState().Entry(context);


}

void AutomatMap_Space7::sp(automatContext& context)
{



}

void AutomatMap_Name1::EOS(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Ok);
    context.getState().Entry(context);


}

void AutomatMap_Name1::ch(automatContext& context)
{



}

void AutomatMap_Name1::num(automatContext& context)
{



}

void AutomatMap_Name1::sp(automatContext& context)
{



}

void AutomatMap_Error::Unknown(automatContext& context)
{



}

//
// Local variables:
//  buffer-read-only: t
// End:
//
