//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : automat.sm
//

#ifndef AUTOMAT_SM_H
#define AUTOMAT_SM_H


#define SMC_USES_IOSTREAMS

#include <statemap.h>

// Forward declarations.
class AutomatMap;
class AutomatMap_Start;
class AutomatMap_Cs;
class AutomatMap_Rs;
class AutomatMap_Es;
class AutomatMap_As;
class AutomatMap_Ts;
class AutomatMap_Es2;
class AutomatMap_Space1;
class AutomatMap_Name;
class AutomatMap_Space2;
class AutomatMap_OpenBracket;
class AutomatMap_Space3;
class AutomatMap_List;
class AutomatMap_Comma;
class AutomatMap_Space4;
class AutomatMap_Close_bracket;
class AutomatMap_As2;
class AutomatMap_Ss;
class AutomatMap_Space5;
class AutomatMap_Name0;
class AutomatMap_Space6;
class AutomatMap_Js;
class AutomatMap_Os;
class AutomatMap_Is;
class AutomatMap_Ns;
class AutomatMap_Space7;
class AutomatMap_Name1;
class AutomatMap_Error;
class AutomatMap_Ok;
class AutomatMap_Default;
class AutomatState;
class automatContext;
class Automat;

class AutomatState :
    public statemap::State
{
public:

    AutomatState(const char * const name, const int stateId)
    : statemap::State(name, stateId)
    {};

    virtual void Entry(automatContext&) {};
    virtual void Exit(automatContext&) {};

    virtual void EOS(automatContext& context);
    virtual void Unknown(automatContext& context);
    virtual void c_b(automatContext& context);
    virtual void ch(automatContext& context, char c);
    virtual void comma(automatContext& context);
    virtual void num(automatContext& context, char c);
    virtual void o_b(automatContext& context);
    virtual void sp(automatContext& context);
    virtual void start(automatContext& context);

protected:

    virtual void Default(automatContext& context);
};

class AutomatMap
{
public:

    static AutomatMap_Start Start;
    static AutomatMap_Cs Cs;
    static AutomatMap_Rs Rs;
    static AutomatMap_Es Es;
    static AutomatMap_As As;
    static AutomatMap_Ts Ts;
    static AutomatMap_Es2 Es2;
    static AutomatMap_Space1 Space1;
    static AutomatMap_Name Name;
    static AutomatMap_Space2 Space2;
    static AutomatMap_OpenBracket OpenBracket;
    static AutomatMap_Space3 Space3;
    static AutomatMap_List List;
    static AutomatMap_Comma Comma;
    static AutomatMap_Space4 Space4;
    static AutomatMap_Close_bracket Close_bracket;
    static AutomatMap_As2 As2;
    static AutomatMap_Ss Ss;
    static AutomatMap_Space5 Space5;
    static AutomatMap_Name0 Name0;
    static AutomatMap_Space6 Space6;
    static AutomatMap_Js Js;
    static AutomatMap_Os Os;
    static AutomatMap_Is Is;
    static AutomatMap_Ns Ns;
    static AutomatMap_Space7 Space7;
    static AutomatMap_Name1 Name1;
    static AutomatMap_Error Error;
    static AutomatMap_Ok Ok;
};

class AutomatMap_Default :
    public AutomatState
{
public:

    AutomatMap_Default(const char * const name, const int stateId)
    : AutomatState(name, stateId)
    {};

    virtual void Unknown(automatContext& context);
    virtual void ch(automatContext& context, char c);
    virtual void sp(automatContext& context);
    virtual void comma(automatContext& context);
    virtual void o_b(automatContext& context);
    virtual void c_b(automatContext& context);
    virtual void EOS(automatContext& context);
};

class AutomatMap_Start :
    public AutomatMap_Default
{
public:
    AutomatMap_Start(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void ch(automatContext& context, char c);
};

class AutomatMap_Cs :
    public AutomatMap_Default
{
public:
    AutomatMap_Cs(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void ch(automatContext& context, char c);
};

class AutomatMap_Rs :
    public AutomatMap_Default
{
public:
    AutomatMap_Rs(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void ch(automatContext& context, char c);
};

class AutomatMap_Es :
    public AutomatMap_Default
{
public:
    AutomatMap_Es(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void ch(automatContext& context, char c);
};

class AutomatMap_As :
    public AutomatMap_Default
{
public:
    AutomatMap_As(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void ch(automatContext& context, char c);
};

class AutomatMap_Ts :
    public AutomatMap_Default
{
public:
    AutomatMap_Ts(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void ch(automatContext& context, char c);
};

class AutomatMap_Es2 :
    public AutomatMap_Default
{
public:
    AutomatMap_Es2(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void sp(automatContext& context);
};

class AutomatMap_Space1 :
    public AutomatMap_Default
{
public:
    AutomatMap_Space1(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void ch(automatContext& context, char c);
    virtual void num(automatContext& context, char c);
    virtual void sp(automatContext& context);
};

class AutomatMap_Name :
    public AutomatMap_Default
{
public:
    AutomatMap_Name(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void ch(automatContext& context, char c);
    virtual void num(automatContext& context, char c);
    virtual void sp(automatContext& context);
};

class AutomatMap_Space2 :
    public AutomatMap_Default
{
public:
    AutomatMap_Space2(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void ch(automatContext& context, char c);
    virtual void o_b(automatContext& context);
    virtual void sp(automatContext& context);
};

class AutomatMap_OpenBracket :
    public AutomatMap_Default
{
public:
    AutomatMap_OpenBracket(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void sp(automatContext& context);
};

class AutomatMap_Space3 :
    public AutomatMap_Default
{
public:
    AutomatMap_Space3(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void c_b(automatContext& context);
    virtual void ch(automatContext& context, char c);
    virtual void num(automatContext& context, char c);
    virtual void sp(automatContext& context);
};

class AutomatMap_List :
    public AutomatMap_Default
{
public:
    AutomatMap_List(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void ch(automatContext& context, char c);
    virtual void comma(automatContext& context);
    virtual void num(automatContext& context, char c);
    virtual void sp(automatContext& context);
};

class AutomatMap_Comma :
    public AutomatMap_Default
{
public:
    AutomatMap_Comma(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void ch(automatContext& context, char c);
    virtual void num(automatContext& context, char c);
    virtual void sp(automatContext& context);
};

class AutomatMap_Space4 :
    public AutomatMap_Default
{
public:
    AutomatMap_Space4(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void c_b(automatContext& context);
    virtual void sp(automatContext& context);
};

class AutomatMap_Close_bracket :
    public AutomatMap_Default
{
public:
    AutomatMap_Close_bracket(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void EOS(automatContext& context);
};

class AutomatMap_As2 :
    public AutomatMap_Default
{
public:
    AutomatMap_As2(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void ch(automatContext& context, char c);
};

class AutomatMap_Ss :
    public AutomatMap_Default
{
public:
    AutomatMap_Ss(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void sp(automatContext& context);
};

class AutomatMap_Space5 :
    public AutomatMap_Default
{
public:
    AutomatMap_Space5(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void ch(automatContext& context, char c);
    virtual void num(automatContext& context, char c);
    virtual void sp(automatContext& context);
};

class AutomatMap_Name0 :
    public AutomatMap_Default
{
public:
    AutomatMap_Name0(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void ch(automatContext& context, char c);
    virtual void num(automatContext& context, char c);
    virtual void sp(automatContext& context);
};

class AutomatMap_Space6 :
    public AutomatMap_Default
{
public:
    AutomatMap_Space6(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void ch(automatContext& context, char c);
    virtual void sp(automatContext& context);
};

class AutomatMap_Js :
    public AutomatMap_Default
{
public:
    AutomatMap_Js(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void ch(automatContext& context, char c);
};

class AutomatMap_Os :
    public AutomatMap_Default
{
public:
    AutomatMap_Os(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void ch(automatContext& context, char c);
};

class AutomatMap_Is :
    public AutomatMap_Default
{
public:
    AutomatMap_Is(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void ch(automatContext& context, char c);
};

class AutomatMap_Ns :
    public AutomatMap_Default
{
public:
    AutomatMap_Ns(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void sp(automatContext& context);
};

class AutomatMap_Space7 :
    public AutomatMap_Default
{
public:
    AutomatMap_Space7(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void ch(automatContext& context, char c);
    virtual void num(automatContext& context, char c);
    virtual void sp(automatContext& context);
};

class AutomatMap_Name1 :
    public AutomatMap_Default
{
public:
    AutomatMap_Name1(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void EOS(automatContext& context);
    virtual void ch(automatContext& context, char c);
    virtual void num(automatContext& context, char c);
    virtual void sp(automatContext& context);
};

class AutomatMap_Error :
    public AutomatMap_Default
{
public:
    AutomatMap_Error(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void EOS(automatContext& context);
    virtual void Unknown(automatContext& context);
    virtual void c_b(automatContext& context);
    virtual void ch(automatContext& context, char c);
    virtual void comma(automatContext& context);
    virtual void num(automatContext& context, char c);
    virtual void o_b(automatContext& context);
    virtual void sp(automatContext& context);
    virtual void start(automatContext& context);
};

class AutomatMap_Ok :
    public AutomatMap_Default
{
public:
    AutomatMap_Ok(const char * const name, const int stateId)
    : AutomatMap_Default(name, stateId)
    {};

    virtual void start(automatContext& context);
};

class automatContext :
    public statemap::FSMContext
{
public:

    explicit automatContext(Automat& owner)
    : FSMContext(AutomatMap::Start),
      _owner(owner)
    {};

    automatContext(Automat& owner, const statemap::State& state)
    : FSMContext(state),
      _owner(owner)
    {};

    virtual void enterStartState()
    {
        getState().Entry(*this);
        return;
    }

    inline Automat& getOwner()
    {
        return (_owner);
    };

    inline AutomatState& getState()
    {
        if (_state == NULL)
        {
            throw statemap::StateUndefinedException();
        }

        return dynamic_cast<AutomatState&>(*_state);
    };

    inline void EOS()
    {
        getState().EOS(*this);
    };

    inline void Unknown()
    {
        getState().Unknown(*this);
    };

    inline void c_b()
    {
        getState().c_b(*this);
    };

    inline void ch(char c)
    {
        getState().ch(*this, c);
    };

    inline void comma()
    {
        getState().comma(*this);
    };

    inline void num(char c)
    {
        getState().num(*this, c);
    };

    inline void o_b()
    {
        getState().o_b(*this);
    };

    inline void sp()
    {
        getState().sp(*this);
    };

    inline void start()
    {
        getState().start(*this);
    };

private:
    Automat& _owner;
};


#endif // AUTOMAT_SM_H

//
// Local variables:
//  buffer-read-only: t
// End:
//
