//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : automat.sm
//

#include "automat.h"
#include "automat_sm.h"

using namespace statemap;

// Static class declarations.
AutomatMap_Start AutomatMap::Start("AutomatMap::Start", 0);
AutomatMap_Cs AutomatMap::Cs("AutomatMap::Cs", 1);
AutomatMap_Rs AutomatMap::Rs("AutomatMap::Rs", 2);
AutomatMap_Es AutomatMap::Es("AutomatMap::Es", 3);
AutomatMap_As AutomatMap::As("AutomatMap::As", 4);
AutomatMap_Ts AutomatMap::Ts("AutomatMap::Ts", 5);
AutomatMap_Es2 AutomatMap::Es2("AutomatMap::Es2", 6);
AutomatMap_Space1 AutomatMap::Space1("AutomatMap::Space1", 7);
AutomatMap_Name AutomatMap::Name("AutomatMap::Name", 8);
AutomatMap_Space2 AutomatMap::Space2("AutomatMap::Space2", 9);
AutomatMap_OpenBracket AutomatMap::OpenBracket("AutomatMap::OpenBracket", 10);
AutomatMap_Space3 AutomatMap::Space3("AutomatMap::Space3", 11);
AutomatMap_List AutomatMap::List("AutomatMap::List", 12);
AutomatMap_Comma AutomatMap::Comma("AutomatMap::Comma", 13);
AutomatMap_Space4 AutomatMap::Space4("AutomatMap::Space4", 14);
AutomatMap_Close_bracket AutomatMap::Close_bracket("AutomatMap::Close_bracket", 15);
AutomatMap_As2 AutomatMap::As2("AutomatMap::As2", 16);
AutomatMap_Ss AutomatMap::Ss("AutomatMap::Ss", 17);
AutomatMap_Space5 AutomatMap::Space5("AutomatMap::Space5", 18);
AutomatMap_Name0 AutomatMap::Name0("AutomatMap::Name0", 19);
AutomatMap_Space6 AutomatMap::Space6("AutomatMap::Space6", 20);
AutomatMap_Js AutomatMap::Js("AutomatMap::Js", 21);
AutomatMap_Os AutomatMap::Os("AutomatMap::Os", 22);
AutomatMap_Is AutomatMap::Is("AutomatMap::Is", 23);
AutomatMap_Ns AutomatMap::Ns("AutomatMap::Ns", 24);
AutomatMap_Space7 AutomatMap::Space7("AutomatMap::Space7", 25);
AutomatMap_Name1 AutomatMap::Name1("AutomatMap::Name1", 26);
AutomatMap_Error AutomatMap::Error("AutomatMap::Error", 27);
AutomatMap_Ok AutomatMap::Ok("AutomatMap::Ok", 28);

void AutomatState::EOS(automatContext& context)
{
    Default(context);
}

void AutomatState::Unknown(automatContext& context)
{
    Default(context);
}

void AutomatState::c_b(automatContext& context)
{
    Default(context);
}

void AutomatState::ch(automatContext& context, char c)
{
    Default(context);
}

void AutomatState::comma(automatContext& context)
{
    Default(context);
}

void AutomatState::num(automatContext& context, char c)
{
    Default(context);
}

void AutomatState::o_b(automatContext& context)
{
    Default(context);
}

void AutomatState::sp(automatContext& context)
{
    Default(context);
}

void AutomatState::start(automatContext& context)
{
    Default(context);
}

void AutomatState::Default(automatContext& context)
{
    throw (
        TransitionUndefinedException(
            (context.getState()).getName(),
            context.getTransition()));

}

void AutomatMap_Default::Unknown(automatContext& context)
{
    Automat& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setBad();
        context.setState(AutomatMap::Error);
    }
    catch (...)
    {
        context.setState(AutomatMap::Error);
        throw;
    }
    context.getState().Entry(context);


}

void AutomatMap_Default::ch(automatContext& context, char c)
{
    Automat& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setBad();
        context.setState(AutomatMap::Error);
    }
    catch (...)
    {
        context.setState(AutomatMap::Error);
        throw;
    }
    context.getState().Entry(context);


}

void AutomatMap_Default::sp(automatContext& context)
{
    Automat& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setBad();
        context.setState(AutomatMap::Error);
    }
    catch (...)
    {
        context.setState(AutomatMap::Error);
        throw;
    }
    context.getState().Entry(context);


}

void AutomatMap_Default::comma(automatContext& context)
{
    Automat& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setBad();
        context.setState(AutomatMap::Error);
    }
    catch (...)
    {
        context.setState(AutomatMap::Error);
        throw;
    }
    context.getState().Entry(context);


}

void AutomatMap_Default::o_b(automatContext& context)
{
    Automat& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setBad();
        context.setState(AutomatMap::Error);
    }
    catch (...)
    {
        context.setState(AutomatMap::Error);
        throw;
    }
    context.getState().Entry(context);


}

void AutomatMap_Default::c_b(automatContext& context)
{
    Automat& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setBad();
        context.setState(AutomatMap::Error);
    }
    catch (...)
    {
        context.setState(AutomatMap::Error);
        throw;
    }
    context.getState().Entry(context);


}

void AutomatMap_Default::EOS(automatContext& context)
{
    Automat& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setBad();
        context.setState(AutomatMap::Error);
    }
    catch (...)
    {
        context.setState(AutomatMap::Error);
        throw;
    }
    context.getState().Entry(context);


}

void AutomatMap_Start::ch(automatContext& context, char c)
{
    Automat& ctxt = context.getOwner();

    if (c == 'c')
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.setGood();
            ctxt.reset();
            context.setState(AutomatMap::Cs);
        }
        catch (...)
        {
            context.setState(AutomatMap::Cs);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
         AutomatMap_Default::ch(context, c);
    }


}

void AutomatMap_Cs::ch(automatContext& context, char c)
{

    if (c == 'r')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(AutomatMap::Rs);
        context.getState().Entry(context);
    }
    else
    {
         AutomatMap_Default::ch(context, c);
    }


}

void AutomatMap_Rs::ch(automatContext& context, char c)
{

    if (c == 'e')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(AutomatMap::Es);
        context.getState().Entry(context);
    }
    else
    {
         AutomatMap_Default::ch(context, c);
    }


}

void AutomatMap_Es::ch(automatContext& context, char c)
{

    if (c == 'a')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(AutomatMap::As);
        context.getState().Entry(context);
    }
    else
    {
         AutomatMap_Default::ch(context, c);
    }


}

void AutomatMap_As::ch(automatContext& context, char c)
{

    if (c == 't')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(AutomatMap::Ts);
        context.getState().Entry(context);
    }
    else
    {
         AutomatMap_Default::ch(context, c);
    }


}

void AutomatMap_Ts::ch(automatContext& context, char c)
{

    if (c == 'e')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(AutomatMap::Es2);
        context.getState().Entry(context);
    }
    else
    {
         AutomatMap_Default::ch(context, c);
    }


}

void AutomatMap_Es2::sp(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Space1);
    context.getState().Entry(context);


}

void AutomatMap_Space1::ch(automatContext& context, char c)
{
    Automat& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.add_char(ctxt.buf_name, c);
        context.setState(AutomatMap::Name);
    }
    catch (...)
    {
        context.setState(AutomatMap::Name);
        throw;
    }
    context.getState().Entry(context);


}

void AutomatMap_Space1::num(automatContext& context, char c)
{
    Automat& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setBad();
        ctxt.reset();
        context.setState(AutomatMap::Error);
    }
    catch (...)
    {
        context.setState(AutomatMap::Error);
        throw;
    }
    context.getState().Entry(context);


}

void AutomatMap_Space1::sp(automatContext& context)
{



}

void AutomatMap_Name::ch(automatContext& context, char c)
{
    Automat& ctxt = context.getOwner();

    AutomatState& endState = context.getState();

    context.clearState();
    try
    {
        ctxt.add_char(ctxt.buf_name, c);
        context.setState(endState);
    }
    catch (...)
    {
        context.setState(endState);
        throw;
    }


}

void AutomatMap_Name::num(automatContext& context, char c)
{
    Automat& ctxt = context.getOwner();

    AutomatState& endState = context.getState();

    context.clearState();
    try
    {
        ctxt.add_char(ctxt.buf_name, c);
        context.setState(endState);
    }
    catch (...)
    {
        context.setState(endState);
        throw;
    }


}

void AutomatMap_Name::sp(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Space2);
    context.getState().Entry(context);


}

void AutomatMap_Space2::ch(automatContext& context, char c)
{

    if (c == 'a')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(AutomatMap::As2);
        context.getState().Entry(context);
    }
    else
    {
         AutomatMap_Default::ch(context, c);
    }


}

void AutomatMap_Space2::o_b(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::OpenBracket);
    context.getState().Entry(context);


}

void AutomatMap_Space2::sp(automatContext& context)
{



}

void AutomatMap_OpenBracket::sp(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Space3);
    context.getState().Entry(context);


}

void AutomatMap_Space3::c_b(automatContext& context)
{
    Automat& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setBad();
        ctxt.reset();
        context.setState(AutomatMap::Error);
    }
    catch (...)
    {
        context.setState(AutomatMap::Error);
        throw;
    }
    context.getState().Entry(context);


}

void AutomatMap_Space3::ch(automatContext& context, char c)
{
    Automat& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.add_char(ctxt.buf_one_atr, c);
        context.setState(AutomatMap::List);
    }
    catch (...)
    {
        context.setState(AutomatMap::List);
        throw;
    }
    context.getState().Entry(context);


}

void AutomatMap_Space3::num(automatContext& context, char c)
{
    Automat& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setBad();
        ctxt.reset();
        context.setState(AutomatMap::Error);
    }
    catch (...)
    {
        context.setState(AutomatMap::Error);
        throw;
    }
    context.getState().Entry(context);


}

void AutomatMap_Space3::sp(automatContext& context)
{



}

void AutomatMap_List::ch(automatContext& context, char c)
{
    Automat& ctxt = context.getOwner();

    AutomatState& endState = context.getState();

    context.clearState();
    try
    {
        ctxt.add_char(ctxt.buf_one_atr, c);
        context.setState(endState);
    }
    catch (...)
    {
        context.setState(endState);
        throw;
    }


}

void AutomatMap_List::comma(automatContext& context)
{
    Automat& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.add_all_atr();
        ctxt.reset_buf_atr();
        context.setState(AutomatMap::Comma);
    }
    catch (...)
    {
        context.setState(AutomatMap::Comma);
        throw;
    }
    context.getState().Entry(context);


}

void AutomatMap_List::num(automatContext& context, char c)
{
    Automat& ctxt = context.getOwner();

    AutomatState& endState = context.getState();

    context.clearState();
    try
    {
        ctxt.add_char(ctxt.buf_one_atr, c);
        context.setState(endState);
    }
    catch (...)
    {
        context.setState(endState);
        throw;
    }


}

void AutomatMap_List::sp(automatContext& context)
{
    Automat& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.add_all_atr();
        ctxt.reset_buf_atr();
        context.setState(AutomatMap::Space4);
    }
    catch (...)
    {
        context.setState(AutomatMap::Space4);
        throw;
    }
    context.getState().Entry(context);


}

void AutomatMap_Comma::ch(automatContext& context, char c)
{
    Automat& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.add_char(ctxt.buf_one_atr, c);
        context.setState(AutomatMap::List);
    }
    catch (...)
    {
        context.setState(AutomatMap::List);
        throw;
    }
    context.getState().Entry(context);


}

void AutomatMap_Comma::num(automatContext& context, char c)
{
    Automat& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setBad();
        ctxt.reset();
        context.setState(AutomatMap::Error);
    }
    catch (...)
    {
        context.setState(AutomatMap::Error);
        throw;
    }
    context.getState().Entry(context);


}

void AutomatMap_Comma::sp(automatContext& context)
{
    Automat& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setBad();
        ctxt.reset();
        context.setState(AutomatMap::Error);
    }
    catch (...)
    {
        context.setState(AutomatMap::Error);
        throw;
    }
    context.getState().Entry(context);


}

void AutomatMap_Space4::c_b(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Close_bracket);
    context.getState().Entry(context);


}

void AutomatMap_Space4::sp(automatContext& context)
{



}

void AutomatMap_Close_bracket::EOS(automatContext& context)
{
    Automat& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setGood();
        context.setState(AutomatMap::Ok);
    }
    catch (...)
    {
        context.setState(AutomatMap::Ok);
        throw;
    }
    context.getState().Entry(context);


}

void AutomatMap_As2::ch(automatContext& context, char c)
{

    if (c == 's')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(AutomatMap::Ss);
        context.getState().Entry(context);
    }
    else
    {
         AutomatMap_Default::ch(context, c);
    }


}

void AutomatMap_Ss::sp(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Space5);
    context.getState().Entry(context);


}

void AutomatMap_Space5::ch(automatContext& context, char c)
{
    Automat& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.add_char(ctxt.buf_names_connect1, c);
        context.setState(AutomatMap::Name0);
    }
    catch (...)
    {
        context.setState(AutomatMap::Name0);
        throw;
    }
    context.getState().Entry(context);


}

void AutomatMap_Space5::num(automatContext& context, char c)
{
    Automat& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setBad();
        ctxt.reset();
        context.setState(AutomatMap::Error);
    }
    catch (...)
    {
        context.setState(AutomatMap::Error);
        throw;
    }
    context.getState().Entry(context);


}

void AutomatMap_Space5::sp(automatContext& context)
{



}

void AutomatMap_Name0::ch(automatContext& context, char c)
{
    Automat& ctxt = context.getOwner();

    AutomatState& endState = context.getState();

    context.clearState();
    try
    {
        ctxt.add_char(ctxt.buf_names_connect1, c);
        context.setState(endState);
    }
    catch (...)
    {
        context.setState(endState);
        throw;
    }


}

void AutomatMap_Name0::num(automatContext& context, char c)
{
    Automat& ctxt = context.getOwner();

    AutomatState& endState = context.getState();

    context.clearState();
    try
    {
        ctxt.add_char(ctxt.buf_names_connect1, c);
        context.setState(endState);
    }
    catch (...)
    {
        context.setState(endState);
        throw;
    }


}

void AutomatMap_Name0::sp(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Space6);
    context.getState().Entry(context);


}

void AutomatMap_Space6::ch(automatContext& context, char c)
{

    if (c == 'j')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(AutomatMap::Js);
        context.getState().Entry(context);
    }
    else
    {
         AutomatMap_Default::ch(context, c);
    }


}

void AutomatMap_Space6::sp(automatContext& context)
{



}

void AutomatMap_Js::ch(automatContext& context, char c)
{

    if (c == 'o')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(AutomatMap::Os);
        context.getState().Entry(context);
    }
    else
    {
         AutomatMap_Default::ch(context, c);
    }


}

void AutomatMap_Os::ch(automatContext& context, char c)
{

    if (c == 'i')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(AutomatMap::Is);
        context.getState().Entry(context);
    }
    else
    {
         AutomatMap_Default::ch(context, c);
    }


}

void AutomatMap_Is::ch(automatContext& context, char c)
{

    if (c == 'n')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(AutomatMap::Ns);
        context.getState().Entry(context);
    }
    else
    {
         AutomatMap_Default::ch(context, c);
    }


}

void AutomatMap_Ns::sp(automatContext& context)
{

    context.getState().Exit(context);
    context.setState(AutomatMap::Space7);
    context.getState().Entry(context);


}

void AutomatMap_Space7::ch(automatContext& context, char c)
{
    Automat& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.add_char(ctxt.buf_names_connect2, c);
        context.setState(AutomatMap::Name1);
    }
    catch (...)
    {
        context.setState(AutomatMap::Name1);
        throw;
    }
    context.getState().Entry(context);


}

void AutomatMap_Space7::num(automatContext& context, char c)
{
    Automat& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setBad();
        ctxt.reset();
        context.setState(AutomatMap::Error);
    }
    catch (...)
    {
        context.setState(AutomatMap::Error);
        throw;
    }
    context.getState().Entry(context);


}

void AutomatMap_Space7::sp(automatContext& context)
{



}

void AutomatMap_Name1::EOS(automatContext& context)
{
    Automat& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setGood();
        context.setState(AutomatMap::Ok);
    }
    catch (...)
    {
        context.setState(AutomatMap::Ok);
        throw;
    }
    context.getState().Entry(context);


}

void AutomatMap_Name1::ch(automatContext& context, char c)
{
    Automat& ctxt = context.getOwner();

    AutomatState& endState = context.getState();

    context.clearState();
    try
    {
        ctxt.add_char(ctxt.buf_names_connect2, c);
        context.setState(endState);
    }
    catch (...)
    {
        context.setState(endState);
        throw;
    }


}

void AutomatMap_Name1::num(automatContext& context, char c)
{
    Automat& ctxt = context.getOwner();

    AutomatState& endState = context.getState();

    context.clearState();
    try
    {
        ctxt.add_char(ctxt.buf_names_connect2, c);
        context.setState(endState);
    }
    catch (...)
    {
        context.setState(endState);
        throw;
    }


}

void AutomatMap_Name1::sp(automatContext& context)
{



}

void AutomatMap_Error::EOS(automatContext& context)
{



}

void AutomatMap_Error::Unknown(automatContext& context)
{



}

void AutomatMap_Error::c_b(automatContext& context)
{



}

void AutomatMap_Error::ch(automatContext& context, char c)
{



}

void AutomatMap_Error::comma(automatContext& context)
{



}

void AutomatMap_Error::num(automatContext& context, char c)
{



}

void AutomatMap_Error::o_b(automatContext& context)
{



}

void AutomatMap_Error::sp(automatContext& context)
{



}

void AutomatMap_Error::start(automatContext& context)
{
    Automat& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.reset();
        context.setState(AutomatMap::Start);
    }
    catch (...)
    {
        context.setState(AutomatMap::Start);
        throw;
    }
    context.getState().Entry(context);


}

void AutomatMap_Ok::start(automatContext& context)
{
    Automat& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.reset();
        ctxt.setGood();
        context.setState(AutomatMap::Start);
    }
    catch (...)
    {
        context.setState(AutomatMap::Start);
        throw;
    }
    context.getState().Entry(context);


}

//
// Local variables:
//  buffer-read-only: t
// End:
//
